/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PayableOverrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type {
  FunctionFragment,
  Result,
  EventFragment,
} from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "../common";

export interface CampaignInterface extends utils.Interface {
  functions: {
    "claimFunds()": FunctionFragment;
    "donate()": FunctionFragment;
    "getAmountCollected()": FunctionFragment;
    "getDonationBalance(address)": FunctionFragment;
    "getDonationsCounter()": FunctionFragment;
    "getEndDate()": FunctionFragment;
    "getGoalAmount()": FunctionFragment;
    "getRefund()": FunctionFragment;
    "getStartDate()": FunctionFragment;
    "isGoalReached()": FunctionFragment;
    "owner()": FunctionFragment;
    "renounceOwnership()": FunctionFragment;
    "transferOwnership(address)": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "claimFunds"
      | "donate"
      | "getAmountCollected"
      | "getDonationBalance"
      | "getDonationsCounter"
      | "getEndDate"
      | "getGoalAmount"
      | "getRefund"
      | "getStartDate"
      | "isGoalReached"
      | "owner"
      | "renounceOwnership"
      | "transferOwnership"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "claimFunds",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "donate", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "getAmountCollected",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getDonationBalance",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "getDonationsCounter",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getEndDate",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getGoalAmount",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "getRefund", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "getStartDate",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "isGoalReached",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [PromiseOrValue<string>]
  ): string;

  decodeFunctionResult(functionFragment: "claimFunds", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "donate", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getAmountCollected",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getDonationBalance",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getDonationsCounter",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getEndDate", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getGoalAmount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getRefund", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getStartDate",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isGoalReached",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;

  events: {
    "FundsClaimed(address,uint256)": EventFragment;
    "OwnershipTransferred(address,address)": EventFragment;
    "Received(address,uint256)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "FundsClaimed"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "OwnershipTransferred"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "Received"): EventFragment;
}

export interface FundsClaimedEventObject {
  _from: string;
  _value: BigNumber;
}
export type FundsClaimedEvent = TypedEvent<
  [string, BigNumber],
  FundsClaimedEventObject
>;

export type FundsClaimedEventFilter = TypedEventFilter<FundsClaimedEvent>;

export interface OwnershipTransferredEventObject {
  previousOwner: string;
  newOwner: string;
}
export type OwnershipTransferredEvent = TypedEvent<
  [string, string],
  OwnershipTransferredEventObject
>;

export type OwnershipTransferredEventFilter =
  TypedEventFilter<OwnershipTransferredEvent>;

export interface ReceivedEventObject {
  arg0: string;
  arg1: BigNumber;
}
export type ReceivedEvent = TypedEvent<
  [string, BigNumber],
  ReceivedEventObject
>;

export type ReceivedEventFilter = TypedEventFilter<ReceivedEvent>;

export interface Campaign extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: CampaignInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    claimFunds(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    donate(
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    getAmountCollected(overrides?: CallOverrides): Promise<[BigNumber]>;

    getDonationBalance(
      _address: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    getDonationsCounter(overrides?: CallOverrides): Promise<[BigNumber]>;

    getEndDate(overrides?: CallOverrides): Promise<[BigNumber]>;

    getGoalAmount(overrides?: CallOverrides): Promise<[BigNumber]>;

    getRefund(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    getStartDate(overrides?: CallOverrides): Promise<[BigNumber]>;

    isGoalReached(overrides?: CallOverrides): Promise<[boolean]>;

    owner(overrides?: CallOverrides): Promise<[string]>;

    renounceOwnership(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    transferOwnership(
      newOwner: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;
  };

  claimFunds(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  donate(
    overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  getAmountCollected(overrides?: CallOverrides): Promise<BigNumber>;

  getDonationBalance(
    _address: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  getDonationsCounter(overrides?: CallOverrides): Promise<BigNumber>;

  getEndDate(overrides?: CallOverrides): Promise<BigNumber>;

  getGoalAmount(overrides?: CallOverrides): Promise<BigNumber>;

  getRefund(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  getStartDate(overrides?: CallOverrides): Promise<BigNumber>;

  isGoalReached(overrides?: CallOverrides): Promise<boolean>;

  owner(overrides?: CallOverrides): Promise<string>;

  renounceOwnership(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  transferOwnership(
    newOwner: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    claimFunds(overrides?: CallOverrides): Promise<void>;

    donate(overrides?: CallOverrides): Promise<void>;

    getAmountCollected(overrides?: CallOverrides): Promise<BigNumber>;

    getDonationBalance(
      _address: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getDonationsCounter(overrides?: CallOverrides): Promise<BigNumber>;

    getEndDate(overrides?: CallOverrides): Promise<BigNumber>;

    getGoalAmount(overrides?: CallOverrides): Promise<BigNumber>;

    getRefund(overrides?: CallOverrides): Promise<void>;

    getStartDate(overrides?: CallOverrides): Promise<BigNumber>;

    isGoalReached(overrides?: CallOverrides): Promise<boolean>;

    owner(overrides?: CallOverrides): Promise<string>;

    renounceOwnership(overrides?: CallOverrides): Promise<void>;

    transferOwnership(
      newOwner: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {
    "FundsClaimed(address,uint256)"(
      _from?: PromiseOrValue<string> | null,
      _value?: null
    ): FundsClaimedEventFilter;
    FundsClaimed(
      _from?: PromiseOrValue<string> | null,
      _value?: null
    ): FundsClaimedEventFilter;

    "OwnershipTransferred(address,address)"(
      previousOwner?: PromiseOrValue<string> | null,
      newOwner?: PromiseOrValue<string> | null
    ): OwnershipTransferredEventFilter;
    OwnershipTransferred(
      previousOwner?: PromiseOrValue<string> | null,
      newOwner?: PromiseOrValue<string> | null
    ): OwnershipTransferredEventFilter;

    "Received(address,uint256)"(arg0?: null, arg1?: null): ReceivedEventFilter;
    Received(arg0?: null, arg1?: null): ReceivedEventFilter;
  };

  estimateGas: {
    claimFunds(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    donate(
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    getAmountCollected(overrides?: CallOverrides): Promise<BigNumber>;

    getDonationBalance(
      _address: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getDonationsCounter(overrides?: CallOverrides): Promise<BigNumber>;

    getEndDate(overrides?: CallOverrides): Promise<BigNumber>;

    getGoalAmount(overrides?: CallOverrides): Promise<BigNumber>;

    getRefund(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    getStartDate(overrides?: CallOverrides): Promise<BigNumber>;

    isGoalReached(overrides?: CallOverrides): Promise<BigNumber>;

    owner(overrides?: CallOverrides): Promise<BigNumber>;

    renounceOwnership(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    transferOwnership(
      newOwner: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    claimFunds(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    donate(
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    getAmountCollected(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getDonationBalance(
      _address: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getDonationsCounter(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getEndDate(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getGoalAmount(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getRefund(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    getStartDate(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    isGoalReached(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    owner(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    renounceOwnership(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    transferOwnership(
      newOwner: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;
  };
}
